version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: FD_Aggregator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4444
    ports:
      - "5432:5432"


  redis:
    image: "bitnami/redis:7.4.0"
    container_name: "bitnami_redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    # volumes:
    #   - ./redis:/bitnami/redis/data

  redisinsight:
    image: "redis/redisinsight:2.52"
    container_name: "redisinsight"
    ports:
      - "5540:5540"

#
#  redis:
#    image: bitnami/redis:7.4.0
#    container_name: bitnami_redis
#    ports:
#      - "6379:6379"
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#      - REDIS_PORT_NUMBER=6379

